[package]
name = "rust_hypervisor"
version = "0.1.0"
authors = ["Siran Li <953760237@qq.com>"]
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
debug = true

[dependencies]
vm-fdt = { git = "https://github.com/OhmR/vm-fdt" }
#nostd_async = "0.6.0"
#woke = "0.0.2"
fdt = { path = "libfdt-binding" }
log = { version = "0.4", features = ["max_level_trace", "release_max_level_trace"] }
volatile = "0.4.4"
spin = { version = "0.9.4", features = ["use_ticket_mutex"] }
cortex-a = "7.4.0"
buddy_system_allocator = "0.8.0"

[dependencies.tock-registers]
version = "0.7.0"
default-features = false
features = ["register_types"]

[features]
tx2 = []
qemu = []
pi4 = []
update = []
